name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make giftcardwriter_crash1
      - run: make giftcardwriter_crash2
      - run: make giftcardwriter_hang
      - run: make giftcardreader
      - run: make cov1
      - run: make cov2
      - run: make giftcardreader
      - run: gcc -g --coverage giftcardreader.c -o giftcardreader
      - run: ./giftcardreader 1 crash1.gft
      - run: ./giftcardreader 1 crash2.gft
      - run: ./giftcardreader 1 hang.gft
      - run: ./giftcardreader 1 cov1.gft 
      - run: ./giftcardreader 1 cov2.gft 
      - run: ./giftcardreader 1 fuzzer1.gft
      - run: ./giftcardreader 1 fuzzer2.gft
      - run: ./giftcardreader 1 fuzzer3.gft
      - run: gcov giftcardreader
